INSERT INTO categorias ( nombre) VALUES ('Tazas');
INSERT INTO categorias ( nombre) VALUES ('Camisetas');
INSERT INTO categorias ( nombre) VALUES ('Stickers');
INSERT INTO categorias ( nombre) VALUES ('Peluches');

ALTER TABLE productos ADD COLUMN altImagen VARCHAR(1000);

INSERT INTO productos (nombre, descripcion, imagen, altImagen, precio, descuento, categoria_id) VALUES ('Taza de cabeza maliciosa', 'El poder de Mauricio en la palma de tu mano.', 'https://newbloodstore.com/cdn/shop/files/NB_MauriceMug_13.png?v=1746712597', 'Taza de mauricio', 25.99, 0, 1);
INSERT INTO productos (nombre, descripcion, imagen, altImagen, precio, descuento, categoria_id) VALUES ('Camiseta de la prision de carne', 'sinceramente, la prision de carne es mas comoda por dentro de lo que parece.', 'https://newbloodstore.com/cdn/shop/files/ChompMock.png?v=1707976258', 'camiseta de carne', 14.99, 0, 2);
INSERT INTO productos (nombre, descripcion, imagen, altImagen, precio, descuento, categoria_id) VALUES ('pack de Stickers de Ultrakill', 'ni los horrores del infierno, ni maquinas de guerra, ni siquiera los mismisimos arcangeles se libran de ser convertidos en productos a buen precio.', 'https://newbloodstore.com/cdn/shop/files/Stickersultrakill.png?v=1732618673', 'Stickers varios', 1.99, 0, 3);
INSERT INTO productos (nombre, descripcion, imagen, altImagen, precio, descuento, categoria_id) VALUES ('Peluche oficial de V1', 'el glorioso muñeco de peluche oficial de tu maquina asesina favorita.', 'https://newbloodstore.com/cdn/shop/files/Ultraplush_V1_blue_Plush_Toy-SV5-P-1.png?v=1741125476', 'Muñeco de V1', 20.99, 0, 4);
INSERT INTO productos (nombre, descripcion, imagen, altImagen, precio, descuento, categoria_id) VALUES ('Taza de V1', 'la maquina se volvió 2D y ahora está atrapada en esta taza.', 'https://ih1.redbubble.net/image.4689266823.5560/mug,standard,x334,right-pad,600x600,f8f8f8.jpg', 'Taza de Ultrakill', 19.99, 0, 1);
INSERT INTO productos (nombre, descripcion, imagen, altImagen, precio, descuento, categoria_id) VALUES ('Camiseta del arrepentimiento', 'de lo que no te vas ha arrepentir es de comprar en esta tienda.', 'https://newbloodstore.com/cdn/shop/products/repent_shirt_mock.png?v=1644978203&width=900', 'camiseta de virtud', 12.99, 0, 2);
INSERT INTO productos (nombre, descripcion, imagen, altImagen, precio, descuento, categoria_id) VALUES ('mega pack de Stickers', 'en algun momento te tienes que preguntar cuantos stickers son demasiados stickers y la respuesta es que nunca hay demasiados stickers.', 'https://down-ph.img.susercontent.com/file/sg-11134201-7rd3z-lwi0vec62pi266', 'demasiados Stickers', 5.99, 0, 3);
INSERT INTO productos (nombre, descripcion, imagen, altImagen, precio, descuento, categoria_id) VALUES ('Peluche oficial de Gabriel', 'El señor: "CONTEMPLA ¡EL PODER DE UN ANGEL!" vs las monedas en mi bolsillo.', 'https://cdn.shopify.com/s/files/1/0125/8261/7145/files/GABRIEL_Plush_Toy-SV3-P-1_7dfb377b-471f-47c5-871f-0a5a6d6446a8_1000x.png.webp?v=1740416639', 'Muñeco de Gabriel', 20.99, 0, 4);
